# This workflow will install project dependencies and run linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Check lockfile
        run: uv lock --check
      - name: Lint with ruff
        run: |
          # Fail if codebase contains any of these issues
          uv run ruff check .
          uv run ruff format --check .
      - name: Static Typechecking with mypy
        run: |
          uv run mypy --config-file pyproject.toml .
